// Generated by accel/tools/gen_decl.py from this Mac's kernel collections. Do not edit.
// macOS 14.8.9 (23J631)
#pragma once
#include <IOKit/IOService.h>
#include <IOKit/IORangeAllocator.h>
#include <IOKit/IOMemoryDescriptor.h>

typedef uint64_t n_ret;   // a slot whose return type we don't use

struct task;
class IOAccelAllocationInfo;
class IOAccelClientSharedRO;
class IOAccelClientSharedRW;
class IOAccelCommandDescriptor;
class IOAccelConfig;
class IOAccelDisplayMachine;
class IOAccelEvent;
class IOAccelEventMachine2;
class IOAccelEventMachineFast2;
class IOAccelEventQueue;
class IOAccelMemory;
class IOAccelMemoryMap;
class IOAccelResource2;
class IOAccelShared2;
class IOAccelSurface;
class IOAccelSysMemory;
class IOAccelTask;
class IOAccelVidMemory;
class IOFramebuffer;
class IOGraphicsAccelerator2;
class IOPCIDevice;
class IOSurface;
class vendevtBarrierRec;
class vendevtCommandRec;

class IOGraphicsAccelerator2 : public IOService {
	OSDeclareAbstractStructors(IOGraphicsAccelerator2)
public:
	/*  18 */ virtual void free() override;
	/*  96 */ virtual IOReturn setProperties(OSObject *) override;
	/* 127 */ virtual bool requestTerminate(IOService *, IOOptionBits) override;
	/* 129 */ virtual bool didTerminate(IOService *, IOOptionBits, bool *) override;
	/* 133 */ virtual IOReturn configureReport(IOReportChannelList *, IOReportConfigureAction, void *, void *) override;
	/* 134 */ virtual IOReturn updateReport(IOReportChannelList *, IOReportUpdateAction, void *, void *) override;
	/* 184 */ virtual bool start(IOService *) override;
	/* 185 */ virtual void stop(IOService *) override;
	/* 192 */ virtual bool terminate(IOOptionBits) override;
	/* 193 */ virtual bool finalize(IOOptionBits) override;
	/* 209 */ virtual IOWorkLoop * getWorkLoop() const override;
	/* 229 */ virtual IOReturn requestProbe(IOOptionBits) override;
	/* 230 */ virtual IOReturn message(UInt32, IOService *, void *) override;
	/* 239 */ virtual IOReturn newUserClient(task_t, void *, UInt32, IOUserClient **) override;
	/* 266 */ virtual n_ret acceleratorDidLock(char const*, int);
	/* 267 */ virtual n_ret acceleratorWillUnlock(char const*, int);
	/* 268 */ virtual n_ret tmpTotalVRAM();
	/* 269 */ virtual n_ret totalTextureMemory();
	/* 270 */ virtual n_ret isIdle();
	/* 271 */ virtual IOMemoryDescriptor * getStampMemory(unsigned int*) = 0;
	/* 272 */ virtual n_ret createEventMachine();
	/* 273 */ virtual IOAccelEventMachine2 * newEventMachine() = 0;
	/* 274 */ virtual n_ret newClientSharedRO();
	/* 275 */ virtual n_ret newClientSharedRW();
	/* 276 */ virtual n_ret deleteClientSharedRO(IOAccelClientSharedRO*);
	/* 277 */ virtual n_ret deleteClientSharedRW(IOAccelClientSharedRW*);
	/* 278 */ virtual n_ret createShared(task*);
	/* 279 */ virtual n_ret createSysMemory();
	/* 280 */ virtual n_ret createVidMemory(IOAccelShared2*, IOAccelResource2*, unsigned long long, void*);
	/* 281 */ virtual n_ret createMemoryMap(IOAccelTask*, IOAccelMemory*, unsigned int);
	/* 282 */ virtual n_ret createResource(IOAccelShared2*, unsigned int);
	/* 283 */ virtual n_ret createCommandDescriptor();
	/* 284 */ virtual n_ret deleteCommandDescriptor(IOAccelCommandDescriptor*);
	/* 285 */ virtual n_ret newBlockFence();
	/* 286 */ virtual n_ret scrubEvents();
	/* 287 */ virtual n_ret createDrawable(IOAccelSurface*, IOAccelShared2*, bool);
	/* 288 */ virtual n_ret resourceTypeForIOSurface(IOSurface*);
	/* 289 */ virtual n_ret createDisplayPipe(IOFramebuffer*, unsigned int);
	/* 290 */ virtual n_ret createMemoryDescriptorWithAddressRange(unsigned long long, unsigned long long, unsigned int, task*);
	/* 291 */ virtual n_ret createMemoryDescriptorWithPersistentMemoryDescriptor(IOMemoryDescriptor*);
	/* 292 */ virtual n_ret createBufferMemoryDescriptorWithOptions(unsigned int, unsigned long, unsigned long);
	/* 293 */ virtual n_ret createBufferMemoryDescriptorInTaskWithOptions(task*, unsigned int, unsigned long, unsigned long);
	/* 294 */ virtual n_ret freeAllGPUMappings();
	/* 295 */ virtual n_ret freeWaitToPrepareVidMemory(IOAccelVidMemory*, bool, bool);
	/* 296 */ virtual n_ret freeWaitToPrepareVidMap(IOAccelMemoryMap*, bool, bool);
	/* 297 */ virtual n_ret unwireAllVidMemory();
	/* 298 */ virtual n_ret freeAllVidMemoryMappings();
	/* 299 */ virtual n_ret pageoffSurfaceInLinear();
	/* 300 */ virtual n_ret freeWaitToPrepareSysMemory(IOAccelSysMemory*, bool);
	/* 301 */ virtual n_ret freeWaitToPrepareSysMap(IOAccelMemoryMap*, bool);
	/* 302 */ virtual n_ret collectGartWirings();
	/* 303 */ virtual n_ret unwireAllSysMemory();
	/* 304 */ virtual n_ret freeAllSysMemoryMappings();
	/* 305 */ virtual n_ret getMaxSingleSysMemorySize();
	/* 306 */ virtual n_ret getMaxWiredSysMemorySize();
	/* 307 */ virtual IOAccelTask * createUserGPUTask() = 0;
	/* 308 */ virtual n_ret acceleratorFinalize();
	/* 309 */ virtual n_ret submitSwapCopy(IOAccelEvent*, IOAccelResource2*, IOAccelResource2*);
	/* 310 */ virtual void populateAccelConfig(IOAccelConfig*) = 0;
	/* 311 */ virtual n_ret calcMaxGPUPhysicalMemoryBytes(unsigned long long);
	/* 312 */ virtual bool configureDevice(IOPCIDevice*) = 0;
	/* 313 */ virtual void teardownDevice(IOPCIDevice*) = 0;
	/* 314 */ virtual IOAccelTask * createKernelGPUTask() = 0;
	/* 315 */ virtual n_ret systemWillSleep();
	/* 316 */ virtual n_ret systemDidWake();
	/* 317 */ virtual n_ret systemWillChangeSpeed();
	/* 318 */ virtual n_ret systemDidChangeSpeed();
	/* 319 */ virtual n_ret configIsHeadless();
	/* 320 */ virtual IOAccelDisplayMachine * newDisplayMachine() = 0;
	/* 321 */ virtual n_ret newShared();
	/* 322 */ virtual n_ret newSharedUserClient();
	/* 323 */ virtual n_ret newDevice();
	/* 324 */ virtual void * newGLContext() = 0;
	/* 325 */ virtual void * newCLContext() = 0;
	/* 326 */ virtual void * newSurface() = 0;
	/* 327 */ virtual void * new2DContext() = 0;
	/* 328 */ virtual void * newVideoContext() = 0;
	/* 329 */ virtual n_ret newDisplayPipe();
	/* 330 */ virtual n_ret newDrawable();
	/* 331 */ virtual n_ret newContext(unsigned int);
	/* 332 */ virtual void * newSysMemory() = 0;
	/* 333 */ virtual void * newVidMemory() = 0;
	/* 334 */ virtual void * newResource() = 0;
	/* 335 */ virtual n_ret newCommandDescriptor();
	/* 336 */ virtual n_ret newStatistics();
	/* 337 */ virtual void * newMemoryMap() = 0;
	/* 338 */ virtual n_ret getMaxResourceSize();
	/* 339 */ virtual n_ret newRemoteMemory();
	/* 340 */ virtual n_ret createRemoteMemory(IOAccelShared2*, unsigned long long, unsigned int, unsigned int);
	/* 341 */ virtual n_ret newContextEventFence();
	/* 342 */ virtual n_ret createIODMACommand();
	/* 343 */ virtual n_ret triage(char**, unsigned long long*);
	/* 344 */ virtual n_ret _RESERVEDIOGraphicsAccelerator3();
	/* 345 */ virtual n_ret _RESERVEDIOGraphicsAccelerator4();
	/* 346 */ virtual n_ret _RESERVEDIOGraphicsAccelerator5();
	/* 347 */ virtual n_ret describeDriverAllocations(IOAccelAllocationInfo*);
	/* 348 */ virtual n_ret newCommandQueue();
	/* 349 */ virtual n_ret ktraceStateChanged();
	uint8_t _nva_data[0xdd8 - sizeof(IOService)];   // the family's own fields
};
static_assert(sizeof(IOGraphicsAccelerator2) == 0xdd8, "IOGraphicsAccelerator2 size");
#define NVA_IOGraphicsAccelerator2_SLOTS 350

#define NVA_FWD_DEFS_IOGraphicsAccelerator2 \
	__attribute__((naked)) IOWorkLoop * IOGraphicsAccelerator2::getWorkLoop() const { __asm__("movq __ZTV22IOGraphicsAccelerator2@GOTPCREL(%rip), %rax\n\tjmpq *1688(%rax)"); } \
	__attribute__((naked)) n_ret IOGraphicsAccelerator2::tmpTotalVRAM() { __asm__("movq __ZTV22IOGraphicsAccelerator2@GOTPCREL(%rip), %rax\n\tjmpq *2160(%rax)"); } \
	__attribute__((naked)) n_ret IOGraphicsAccelerator2::totalTextureMemory() { __asm__("movq __ZTV22IOGraphicsAccelerator2@GOTPCREL(%rip), %rax\n\tjmpq *2168(%rax)"); }

class IOAccelEventMachine2 : public OSObject {
	OSDeclareAbstractStructors(IOAccelEventMachine2)
public:
	/*  18 */ virtual void free() override;
	/*  35 */ virtual bool init(IOGraphicsAccelerator2*, unsigned int, int);
	/*  36 */ virtual n_ret getClientTestEventFunc() = 0;
	/*  37 */ virtual n_ret getNumStamps();
	/*  38 */ virtual void setStampBaseAddress(unsigned int volatile*);
	/*  39 */ virtual n_ret getStampOffset(int);
	/*  40 */ virtual n_ret initEvent(IOAccelEvent*) = 0;
	/*  41 */ virtual n_ret cleanEvent(IOAccelEvent*) = 0;
	/*  42 */ virtual n_ret finishStamp(int) = 0;
	/*  43 */ virtual n_ret finishAllStamps() = 0;
	/*  44 */ virtual n_ret testStamp(int) = 0;
	/*  45 */ virtual n_ret testAllStamps() = 0;
	/*  46 */ virtual n_ret testAllStampsUnlocked() = 0;
	/*  47 */ virtual n_ret finishEventUnlocked(IOAccelEvent*) = 0;
	/*  48 */ virtual n_ret testEventUnlocked(IOAccelEvent*) = 0;
	/*  49 */ virtual n_ret finishEvent(IOAccelEvent*) = 0;
	/*  50 */ virtual n_ret testEvent(IOAccelEvent*) = 0;
	/*  51 */ virtual n_ret finishEventExcluding(IOAccelEvent*, int) = 0;
	/*  52 */ virtual n_ret testEventExcluding(IOAccelEvent*, int) = 0;
	/*  53 */ virtual n_ret moveEvent(IOAccelEvent*, IOAccelEvent*) = 0;
	/*  54 */ virtual n_ret copyEvent(IOAccelEvent*, IOAccelEvent*) = 0;
	/*  55 */ virtual n_ret mergeEvent(IOAccelEvent*, IOAccelEvent*) = 0;
	/*  56 */ virtual n_ret copyEventExcluding(IOAccelEvent*, IOAccelEvent*, int) = 0;
	/*  57 */ virtual n_ret mergeEventExcluding(IOAccelEvent*, IOAccelEvent*, int) = 0;
	/*  58 */ virtual n_ret setEventStamp(int, IOAccelEvent*) = 0;
	/*  59 */ virtual n_ret incrementStamp(int) = 0;
	/*  60 */ virtual n_ret writeStampCommand(int, IOAccelEventQueue*, vendevtCommandRec*) = 0;
	/*  61 */ virtual n_ret writeEventStampCommand(int, IOAccelEventQueue*, IOAccelEvent*, vendevtCommandRec*) = 0;
	/*  62 */ virtual n_ret writeEventBarrierCommand(IOAccelEventQueue*, IOAccelEvent*, vendevtBarrierRec*, int) = 0;
	/*  63 */ virtual n_ret logCommandSubmission(int) = 0;
	/*  64 */ virtual n_ret stampIsIncremented() = 0;
	/*  65 */ virtual n_ret getStamp(int) = 0;
	/*  66 */ virtual n_ret checkGPUProgress() = 0;
	/*  67 */ virtual n_ret checkChannelProgress(int) = 0;
	/*  68 */ virtual n_ret eventTimeout(int) = 0;
	/*  69 */ virtual n_ret signalStamp(int, unsigned int);
	/*  70 */ virtual n_ret collectAllLiveEventIfNeeded();
	/*  71 */ virtual n_ret waitForStamp(int, unsigned int, unsigned int*);
	/*  72 */ virtual void enableStampInterrupt(int);
	/*  73 */ virtual void disableStampInterrupt(int);
	/*  74 */ virtual n_ret deviceTerminatedUnlocked();
	/*  75 */ virtual n_ret enableEventStampInterrupts(IOAccelEvent const*) = 0;
	/*  76 */ virtual n_ret disableEventStampInterrupts(IOAccelEvent const*) = 0;
	/*  77 */ virtual n_ret stop();
	/*  78 */ virtual n_ret scrubEvent(IOAccelEvent*) = 0;
	/*  79 */ virtual n_ret triage(char**, unsigned long long*) = 0;
	/*  80 */ virtual n_ret _RESERVEDIOAccelEventMachine2();
	/*  81 */ virtual n_ret _RESERVEDIOAccelEventMachine3();
	/*  82 */ virtual n_ret _RESERVEDIOAccelEventMachine4();
	/*  83 */ virtual n_ret _RESERVEDIOAccelEventMachine5();
	uint8_t _nva_data[0xf0 - sizeof(OSObject)];   // the family's own fields
};
static_assert(sizeof(IOAccelEventMachine2) == 0xf0, "IOAccelEventMachine2 size");
#define NVA_IOAccelEventMachine2_SLOTS 84

#define NVA_FWD_DEFS_IOAccelEventMachine2 \
	__attribute__((naked)) n_ret IOAccelEventMachine2::collectAllLiveEventIfNeeded() { __asm__("movq __ZTV20IOAccelEventMachine2@GOTPCREL(%rip), %rax\n\tjmpq *576(%rax)"); }

class IOAccelEventMachineFast2 : public IOAccelEventMachine2 {
	OSDeclareAbstractStructors(IOAccelEventMachineFast2)
public:
	/*  18 */ virtual void free() override;
	/*  35 */ virtual bool init(IOGraphicsAccelerator2*, unsigned int, int) override;
	/*  36 */ virtual n_ret getClientTestEventFunc() override;
	/*  40 */ virtual n_ret initEvent(IOAccelEvent*) override;
	/*  41 */ virtual n_ret cleanEvent(IOAccelEvent*) override;
	/*  42 */ virtual n_ret finishStamp(int) override;
	/*  43 */ virtual n_ret finishAllStamps() override;
	/*  44 */ virtual n_ret testStamp(int) override;
	/*  45 */ virtual n_ret testAllStamps() override;
	/*  46 */ virtual n_ret testAllStampsUnlocked() override;
	/*  47 */ virtual n_ret finishEventUnlocked(IOAccelEvent*) override;
	/*  48 */ virtual n_ret testEventUnlocked(IOAccelEvent*) override;
	/*  49 */ virtual n_ret finishEvent(IOAccelEvent*) override;
	/*  50 */ virtual n_ret testEvent(IOAccelEvent*) override;
	/*  51 */ virtual n_ret finishEventExcluding(IOAccelEvent*, int) override;
	/*  52 */ virtual n_ret testEventExcluding(IOAccelEvent*, int) override;
	/*  53 */ virtual n_ret moveEvent(IOAccelEvent*, IOAccelEvent*) override;
	/*  54 */ virtual n_ret copyEvent(IOAccelEvent*, IOAccelEvent*) override;
	/*  55 */ virtual n_ret mergeEvent(IOAccelEvent*, IOAccelEvent*) override;
	/*  56 */ virtual n_ret copyEventExcluding(IOAccelEvent*, IOAccelEvent*, int) override;
	/*  57 */ virtual n_ret mergeEventExcluding(IOAccelEvent*, IOAccelEvent*, int) override;
	/*  58 */ virtual n_ret setEventStamp(int, IOAccelEvent*) override;
	/*  59 */ virtual n_ret incrementStamp(int) override;
	/*  60 */ virtual n_ret writeStampCommand(int, IOAccelEventQueue*, vendevtCommandRec*) override;
	/*  61 */ virtual n_ret writeEventStampCommand(int, IOAccelEventQueue*, IOAccelEvent*, vendevtCommandRec*) override;
	/*  62 */ virtual n_ret writeEventBarrierCommand(IOAccelEventQueue*, IOAccelEvent*, vendevtBarrierRec*, int) override;
	/*  63 */ virtual n_ret logCommandSubmission(int) override;
	/*  64 */ virtual n_ret stampIsIncremented() override;
	/*  65 */ virtual n_ret getStamp(int) override;
	/*  66 */ virtual n_ret checkGPUProgress() override;
	/*  67 */ virtual n_ret checkChannelProgress(int) override;
	/*  68 */ virtual n_ret eventTimeout(int) override;
	/*  70 */ virtual n_ret collectAllLiveEventIfNeeded() override;
	/*  74 */ virtual n_ret deviceTerminatedUnlocked() override;
	/*  75 */ virtual n_ret enableEventStampInterrupts(IOAccelEvent const*) override;
	/*  76 */ virtual n_ret disableEventStampInterrupts(IOAccelEvent const*) override;
	/*  78 */ virtual n_ret scrubEvent(IOAccelEvent*) override;
	/*  79 */ virtual n_ret triage(char**, unsigned long long*) override;
	/*  84 */ virtual n_ret writeStamp(int, vendevtCommandRec*, unsigned int) = 0;
	/*  85 */ virtual n_ret prepareBarrier(vendevtBarrierRec*) = 0;
	/*  86 */ virtual n_ret completeBarrier(vendevtBarrierRec*) = 0;
	/*  87 */ virtual n_ret writeBarrierElement(vendevtBarrierRec*, int, unsigned int) = 0;
	/*  88 */ virtual n_ret waitForAnyStamp(IOAccelEvent*, int*);
	/*  89 */ virtual n_ret _RESERVEDIOAccelEventMachineFast0();
	/*  90 */ virtual n_ret _RESERVEDIOAccelEventMachineFast1();
	/*  91 */ virtual n_ret _RESERVEDIOAccelEventMachineFast2();
	/*  92 */ virtual n_ret _RESERVEDIOAccelEventMachineFast3();
	/*  93 */ virtual n_ret _RESERVEDIOAccelEventMachineFast4();
	/*  94 */ virtual n_ret _RESERVEDIOAccelEventMachineFast5();
	uint8_t _nva_data[0xd30 - sizeof(IOAccelEventMachine2)];   // the family's own fields
};
static_assert(sizeof(IOAccelEventMachineFast2) == 0xd30, "IOAccelEventMachineFast2 size");
#define NVA_IOAccelEventMachineFast2_SLOTS 95

#define NVA_FWD_DEFS_IOAccelEventMachineFast2 \
	__attribute__((naked)) n_ret IOAccelEventMachineFast2::collectAllLiveEventIfNeeded() { __asm__("movq __ZTV24IOAccelEventMachineFast2@GOTPCREL(%rip), %rax\n\tjmpq *576(%rax)"); }

class IOAccelTask : public OSObject {
	OSDeclareAbstractStructors(IOAccelTask)
public:
	/*   5 */ virtual void release() const override;
	/*  18 */ virtual void free() override;
	/*  35 */ virtual bool init(IOGraphicsAccelerator2*, unsigned int, IORangeAllocator**);
	/*  36 */ virtual n_ret freeToAllocGPUAddress(IOAccelMemoryMap*);
	/*  37 */ virtual n_ret freeAllGPUMappings();
	/*  38 */ virtual n_ret freeAllSysMemoryMappings();
	/*  39 */ virtual n_ret freeAllVidMemoryMappings();
	/*  40 */ virtual n_ret allocate(IOAccelMemoryMap const*);
	/*  41 */ virtual n_ret deallocate(IOAccelMemoryMap const*, unsigned long long);
	/*  42 */ virtual n_ret reserve(unsigned int, unsigned long long, unsigned long long);
	/*  43 */ virtual n_ret describeDriverAllocations(IOAccelAllocationInfo*);
	/*  44 */ virtual n_ret _RESERVEDIOAccelTask0();
	/*  45 */ virtual n_ret _RESERVEDIOAccelTask1();
	/*  46 */ virtual n_ret _RESERVEDIOAccelTask2();
	/*  47 */ virtual n_ret _RESERVEDIOAccelTask3();
	/*  48 */ virtual n_ret _RESERVEDIOAccelTask4();
	/*  49 */ virtual n_ret _RESERVEDIOAccelTask5();
	/*  50 */ virtual n_ret freeWaitToAllocGPUAddress(IOAccelMemoryMap*, bool);
	uint8_t _nva_data[0x258 - sizeof(OSObject)];   // the family's own fields
};
static_assert(sizeof(IOAccelTask) == 0x258, "IOAccelTask size");
#define NVA_IOAccelTask_SLOTS 51

#define NVA_FWD_DEFS_IOAccelTask \
	/* none */

class IOAccelDisplayMachine : public IOService {
	OSDeclareAbstractStructors(IOAccelDisplayMachine)
public:
	/*  18 */ virtual void free() override;
	/* 266 */ virtual n_ret init(IOGraphicsAccelerator2*);
	/* 267 */ virtual n_ret start(IOPCIDevice*);
	/* 268 */ virtual n_ret stop();
	/* 269 */ virtual bool displayModeWillChange() = 0;
	/* 270 */ virtual bool displayModeDidChange() = 0;
	/* 271 */ virtual n_ret initFramebufferResource(unsigned int, unsigned int, IOFramebuffer*, IOAccelResource2*);
	/* 272 */ virtual n_ret destroyFramebufferResource(unsigned int, unsigned int, IOFramebuffer*, IOAccelResource2*);
	/* 273 */ virtual n_ret triage(char**, unsigned long long*);
	/* 274 */ virtual n_ret _RESERVEDIOAccelDisplayMachine1();
	/* 275 */ virtual n_ret _RESERVEDIOAccelDisplayMachine2();
	/* 276 */ virtual n_ret _RESERVEDIOAccelDisplayMachine3();
	/* 277 */ virtual n_ret _RESERVEDIOAccelDisplayMachine4();
	/* 278 */ virtual n_ret _RESERVEDIOAccelDisplayMachine5();
	/* 279 */ virtual n_ret framebuffer_will_power_off(unsigned int);
	/* 280 */ virtual n_ret framebuffer_did_power_on(unsigned int);
	/* 281 */ virtual n_ret display_mode_will_change(unsigned int);
	/* 282 */ virtual n_ret display_mode_did_change(unsigned int);
	/* 283 */ virtual n_ret found_framebuffer(IOFramebuffer*);
	uint8_t _nva_data[0x178 - sizeof(IOService)];   // the family's own fields
};
static_assert(sizeof(IOAccelDisplayMachine) == 0x178, "IOAccelDisplayMachine size");
#define NVA_IOAccelDisplayMachine_SLOTS 284

#define NVA_FWD_DEFS_IOAccelDisplayMachine \
	/* none */

