// Layout probe for GET_GSP_STATIC_INFO and the first alloc/control payloads: compiles NVIDIA's r570.144 SDK control
// headers plus a verbatim copy of GspStaticConfigInfo (gsp_static_config.h, whose
// own includes need NVIDIA's kernel build) and prints src/nv_gsp_static.h.
//
//   make gsp_static_h NVSRC=temp/ogkm/src      (open-gpu-kernel-modules, tag 570.144)
//
// The compiler, not hand arithmetic, decides every offset; the GSP (RV64) uses the
// same natural alignment as x86-64.
#include "nvtypes.h"
#include "ctrl/ctrl0080/ctrl0080gpu.h"
#include "ctrl/ctrl0080/ctrl0080gr.h"
#include "ctrl/ctrl2080/ctrl2080bios.h"
#include "ctrl/ctrl2080/ctrl2080fb.h"
#include "ctrl/ctrl2080/ctrl2080gpu.h"
#include "class/cl0000.h"
#include "class/cl0080.h"
#include "class/cl2080.h"
#include "class/cl90f1.h"
#include "ctrl/ctrl90f1.h"
#include "nvos.h"
#include "alloc/alloc_channel.h"
#include "ctrl/ctrl2080/ctrl2080ce.h"
#include "ctrl/ctrla06f/ctrla06fgpfifo.h"
#include "ctrl/ctrlc36f.h"
#include "class/clb0b5sw.h"
#include "class/cl2080_notification.h"
#include "class/clc46f.h"
#include "class/clc5b5.h"
#include "class/clc5c0.h"
#include "ctrl/ctrl2080/ctrl2080internal.h"
#include "ctrl/ctrl0080/ctrl0080fifo.h"
#include "ctrl/ctrl2080/ctrl2080gr.h"
#include "class/clc597.h"
#include "ctrl/ctrl2080/ctrl2080fifo.h"
#include "class/clc4b0.h"
#include "class/cl0073.h"
#include "ctrl/ctrl0073/ctrl0073system.h"
#include "ctrl/ctrl0073/ctrl0073specific.h"
#include <stdio.h>
#include <stddef.h>
#define NVGPU_ENGINE_CAPS_MASK_ARRAY_MAX ((0x54 - 1) / 32 + 1)   // RM_ENGINE_TYPE_LAST = 0x54
#define MAX_GROUP_COUNT 2                                          // g_gpu_nvoc.h
typedef struct { NvU32 headIndex, maxHResolution, maxVResolution; } VIRTUAL_DISPLAY_GET_MAX_RESOLUTION_PARAMS;
typedef struct { NvU32 numHeads, maxNumHeads; } VIRTUAL_DISPLAY_GET_NUM_HEADS_PARAMS;
typedef struct { NvU32 ecidLow, ecidHigh, ecidExtended; } EcidManufacturingInfo;
typedef struct { NvU64 nonWprHeapOffset, frtsOffset; } FW_WPR_LAYOUT_OFFSET;
typedef struct GspStaticConfigInfo_t
{
    NvU8 grCapsBits[NV0080_CTRL_GR_CAPS_TBL_SIZE];
    NV2080_CTRL_GPU_GET_GID_INFO_PARAMS gidInfo;
    NV2080_CTRL_BIOS_GET_SKU_INFO_PARAMS SKUInfo;
    NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS fbRegionInfoParams;

    NV0080_CTRL_GPU_GET_SRIOV_CAPS_PARAMS sriovCaps;
    NvU32 sriovMaxGfid;

    NvU32 engineCaps[NVGPU_ENGINE_CAPS_MASK_ARRAY_MAX];

    NvBool poisonFuseEnabled;

    NvU64 fb_length;
    NvU64 fbio_mask;
    NvU32 fb_bus_width;
    NvU32 fb_ram_type;
    NvU64 fbp_mask;
    NvU32 l2_cache_size;

    NvU8 gpuNameString[NV2080_GPU_MAX_NAME_STRING_LENGTH];
    NvU8 gpuShortNameString[NV2080_GPU_MAX_NAME_STRING_LENGTH];
    NvU16 gpuNameString_Unicode[NV2080_GPU_MAX_NAME_STRING_LENGTH];
    NvBool bGpuInternalSku;
    NvBool bIsQuadroGeneric;
    NvBool bIsQuadroAd;
    NvBool bIsNvidiaNvs;
    NvBool bIsVgx;
    NvBool bGeforceSmb;
    NvBool bIsTitan;
    NvBool bIsTesla;
    NvBool bIsMobile;
    NvBool bIsGc6Rtd3Allowed;
    NvBool bIsGc8Rtd3Allowed;
    NvBool bIsGcOffRtd3Allowed;
    NvBool bIsGcoffLegacyAllowed;
    NvBool bIsMigSupported;

    /* "Total Board Power" refers to power requirement of GPU,
     * while in GC6 state. Majority of this power will be used
     * to keep V-RAM active to preserve its content.
     * Some energy maybe consumed by Always-on components on GPU chip.
     * This power will be provided by 3.3v voltage rail.
     */
    NvU16  RTD3GC6TotalBoardPower;

    /* PERST# (i.e. PCI Express Reset) is a sideband signal
     * generated by the PCIe Host to indicate the PCIe devices,
     * that the power-rails and the reference-clock are stable.
     * The endpoint device typically uses this signal as a global reset.
     */
    NvU16  RTD3GC6PerstDelay;

    NvU64 bar1PdeBase;
    NvU64 bar2PdeBase;

    NvBool bVbiosValid;
    NvU32 vbiosSubVendor;
    NvU32 vbiosSubDevice;

    NvBool bPageRetirementSupported;

    NvBool bSplitVasBetweenServerClientRm;

    NvBool bClRootportNeedsNosnoopWAR;

    VIRTUAL_DISPLAY_GET_NUM_HEADS_PARAMS displaylessMaxHeads;
    VIRTUAL_DISPLAY_GET_MAX_RESOLUTION_PARAMS displaylessMaxResolution;
    NvU64 displaylessMaxPixels;

    // Client handle for internal RMAPI control.
    NvHandle hInternalClient;

    // Device handle for internal RMAPI control.
    NvHandle hInternalDevice;

    // Subdevice handle for internal RMAPI control.
    NvHandle hInternalSubdevice;

    NvBool bSelfHostedMode;
    NvBool bAtsSupported;

    NvBool bIsGpuUefi;
    NvBool bIsEfiInit;

    EcidManufacturingInfo ecidInfo[MAX_GROUP_COUNT];

    FW_WPR_LAYOUT_OFFSET fwWprLayoutOffset;
} GspStaticConfigInfo;
#define F(f) printf("#define GSC_%-34s 0x%04zx  // size %zu\n", #f, offsetof(GspStaticConfigInfo, f), sizeof(((GspStaticConfigInfo *)0)->f));
int main(void)
{
    printf("// Generated by tools/gsp_layout_probe.c from NVIDIA open-gpu-kernel-modules 570.144\n"
           "// (MIT). Byte offsets into the GET_GSP_STATIC_INFO payload (GspStaticConfigInfo).\n"
           "#pragma once\n\n");
    printf("#define GSC_SIZE %zu\n", sizeof(GspStaticConfigInfo));
    F(grCapsBits)
    F(gidInfo)
    F(SKUInfo)
    F(fbRegionInfoParams)
    F(sriovCaps)
    F(sriovMaxGfid)
    F(engineCaps)
    F(poisonFuseEnabled)
    F(fb_length)
    F(fbio_mask)
    F(fb_bus_width)
    F(fb_ram_type)
    F(fbp_mask)
    F(l2_cache_size)
    F(gpuNameString)
    F(gpuShortNameString)
    F(gpuNameString_Unicode)
    F(bGpuInternalSku)
    F(bIsQuadroGeneric)
    F(bIsQuadroAd)
    F(bIsNvidiaNvs)
    F(bIsVgx)
    F(bGeforceSmb)
    F(bIsTitan)
    F(bIsTesla)
    F(bIsMobile)
    F(bIsGc6Rtd3Allowed)
    F(bIsGc8Rtd3Allowed)
    F(bIsGcOffRtd3Allowed)
    F(bIsGcoffLegacyAllowed)
    F(bIsMigSupported)
    F(RTD3GC6TotalBoardPower)
    F(RTD3GC6PerstDelay)
    F(bar1PdeBase)
    F(bar2PdeBase)
    F(bVbiosValid)
    F(vbiosSubVendor)
    F(vbiosSubDevice)
    F(bPageRetirementSupported)
    F(bSplitVasBetweenServerClientRm)
    F(bClRootportNeedsNosnoopWAR)
    F(displaylessMaxHeads)
    F(displaylessMaxResolution)
    F(displaylessMaxPixels)
    F(hInternalClient)
    F(hInternalDevice)
    F(hInternalSubdevice)
    F(bSelfHostedMode)
    F(bAtsSupported)
    F(bIsGpuUefi)
    F(bIsEfiInit)
    F(ecidInfo)
    F(fwWprLayoutOffset)
    printf("#define FBR_PARAMS_SIZE %zu\n", sizeof(NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS));
    printf("\n// fbRegionInfoParams (NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS)\n");
    printf("#define FBR_NUM %zu\n", offsetof(NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS, numFBRegions));
    printf("#define FBR_REGIONS %zu\n", offsetof(NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS, fbRegion));
    printf("#define FBR_MAX %d\n", NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_MAX_ENTRIES);
    typedef NV2080_CTRL_CMD_FB_GET_FB_REGION_FB_REGION_INFO R;
    printf("#define FBR_REGION_SIZE %zu\n", sizeof(R));
    printf("#define FBR_BASE %zu\n#define FBR_LIMIT %zu\n#define FBR_RESERVED %zu\n#define FBR_PERFORMANCE %zu\n"
           "#define FBR_COMPRESSED %zu\n#define FBR_ISO %zu\n#define FBR_PROTECTED %zu\n",
           offsetof(R, base), offsetof(R, limit), offsetof(R, reserved), offsetof(R, performance),
           offsetof(R, supportCompressed), offsetof(R, supportISO), offsetof(R, bProtected));

    printf("\n// Object allocation parameters (GSP_RM_ALLOC payloads)\n");
    printf("#define NV01_ROOT_CLASS 0x%x\n#define NV01_DEVICE_0_CLASS 0x%x\n#define NV20_SUBDEVICE_0_CLASS 0x%x\n",
           NV01_ROOT, NV01_DEVICE_0, NV20_SUBDEVICE_0);
    printf("#define NV0000_ALLOC_SIZE %zu\n#define NV0000_hClient %zu\n#define NV0000_processID %zu\n#define NV0000_processName %zu\n",
           sizeof(NV0000_ALLOC_PARAMETERS), offsetof(NV0000_ALLOC_PARAMETERS, hClient),
           offsetof(NV0000_ALLOC_PARAMETERS, processID), offsetof(NV0000_ALLOC_PARAMETERS, processName));
    printf("#define NV0080_ALLOC_SIZE %zu\n#define NV0080_deviceId %zu\n#define NV0080_hClientShare %zu\n",
           sizeof(NV0080_ALLOC_PARAMETERS), offsetof(NV0080_ALLOC_PARAMETERS, deviceId),
           offsetof(NV0080_ALLOC_PARAMETERS, hClientShare));
    printf("#define NV2080_ALLOC_SIZE %zu\n#define NV2080_subDeviceId %zu\n",
           sizeof(NV2080_ALLOC_PARAMETERS), offsetof(NV2080_ALLOC_PARAMETERS, subDeviceId));

    printf("\n// Controls (GSP_RM_CONTROL payloads)\n");
    printf("#define NV2080_CTRL_CMD_GPU_GET_NAME_STRING_ 0x%x\n", NV2080_CTRL_CMD_GPU_GET_NAME_STRING);
    printf("#define NV2080_GET_NAME_SIZE %zu\n#define NV2080_GET_NAME_flags %zu\n#define NV2080_GET_NAME_string %zu\n",
           sizeof(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS),
           offsetof(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS, gpuNameStringFlags),
           offsetof(NV2080_CTRL_GPU_GET_NAME_STRING_PARAMS, gpuNameString));

    printf("\n// VA space (FERMI_VASPACE_A) and its reserved-PDE control (Phase 4 step 4)\n");
    typedef NV_VASPACE_ALLOCATION_PARAMETERS V;
    printf("#define FERMI_VASPACE_A_CLASS 0x%x\n#define NV_VASPACE_ALLOC_SIZE %zu\n", FERMI_VASPACE_A, sizeof(V));
    printf("#define NV_VASPACE_index %zu\n#define NV_VASPACE_flags %zu\n#define NV_VASPACE_vaSize %zu\n"
           "#define NV_VASPACE_bigPageSize %zu\n#define NV_VASPACE_vaBase %zu\n",
           offsetof(V, index), offsetof(V, flags), offsetof(V, vaSize), offsetof(V, bigPageSize), offsetof(V, vaBase));
    typedef NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS C;
    printf("#define NV90F1_CTRL_CMD_VASPACE_COPY_SERVER_RESERVED_PDES_ 0x%x\n#define NV90F1_COPY_PDES_SIZE %zu\n",
           NV90F1_CTRL_CMD_VASPACE_COPY_SERVER_RESERVED_PDES, sizeof(C));
    printf("#define NV90F1_COPY_PDES_hSubDevice %zu\n#define NV90F1_COPY_PDES_subDeviceId %zu\n"
           "#define NV90F1_COPY_PDES_pageSize %zu\n#define NV90F1_COPY_PDES_virtAddrLo %zu\n"
           "#define NV90F1_COPY_PDES_virtAddrHi %zu\n#define NV90F1_COPY_PDES_numLevelsToCopy %zu\n"
           "#define NV90F1_COPY_PDES_levels %zu\n#define NV90F1_COPY_PDES_LEVEL_SIZE %zu\n#define NV90F1_COPY_PDES_MAX_LEVELS %u\n",
           offsetof(C, hSubDevice), offsetof(C, subDeviceId), offsetof(C, pageSize), offsetof(C, virtAddrLo),
           offsetof(C, virtAddrHi), offsetof(C, numLevelsToCopy), offsetof(C, levels), sizeof(((C *)0)->levels[0]),
           (unsigned)GMMU_FMT_MAX_LEVELS);
    printf("#define NV90F1_LEVEL_physAddress %zu\n#define NV90F1_LEVEL_size %zu\n#define NV90F1_LEVEL_aperture %zu\n"
           "#define NV90F1_LEVEL_pageShift %zu\n",
           offsetof(C, levels[0].physAddress), offsetof(C, levels[0].size), offsetof(C, levels[0].aperture),
           offsetof(C, levels[0].pageShift));

    printf("\n// Channel and copy engine (Phase 4 step 5)\n");
    typedef NV_CHANNEL_ALLOC_PARAMS H;
    printf("#define TURING_CHANNEL_GPFIFO_A_CLASS 0x%x\n#define TURING_DMA_COPY_A_CLASS 0x%x\n",
           TURING_CHANNEL_GPFIFO_A, TURING_DMA_COPY_A);
    printf("#define NV_CHAN_ALLOC_SIZE %zu\n#define NV_CHAN_hObjectError %zu\n#define NV_CHAN_gpFifoOffset %zu\n"
           "#define NV_CHAN_gpFifoEntries %zu\n#define NV_CHAN_flags %zu\n#define NV_CHAN_hContextShare %zu\n"
           "#define NV_CHAN_hVASpace %zu\n#define NV_CHAN_engineType %zu\n#define NV_CHAN_subDeviceId %zu\n"
           "#define NV_CHAN_instanceMem %zu\n#define NV_CHAN_userdMem %zu\n#define NV_CHAN_ramfcMem %zu\n"
           "#define NV_CHAN_mthdbufMem %zu\n#define NV_CHAN_internalFlags %zu\n#define NV_CHAN_errorNotifierMem %zu\n",
           sizeof(H), offsetof(H, hObjectError), offsetof(H, gpFifoOffset), offsetof(H, gpFifoEntries),
           offsetof(H, flags), offsetof(H, hContextShare), offsetof(H, hVASpace), offsetof(H, engineType),
           offsetof(H, subDeviceId), offsetof(H, instanceMem), offsetof(H, userdMem), offsetof(H, ramfcMem),
           offsetof(H, mthdbufMem), offsetof(H, internalFlags), offsetof(H, errorNotifierMem));
    typedef NV_MEMORY_DESC_PARAMS M;
    printf("#define NV_MEMDESC_SIZE %zu\n#define NV_MEMDESC_base %zu\n#define NV_MEMDESC_size %zu\n"
           "#define NV_MEMDESC_addressSpace %zu\n#define NV_MEMDESC_cacheAttrib %zu\n",
           sizeof(M), offsetof(M, base), offsetof(M, size), offsetof(M, addressSpace), offsetof(M, cacheAttrib));
    printf("#define NV2080_CTRL_CMD_GPU_GET_ENGINES_V2_ 0x%x\n#define NV2080_GET_ENGINES_SIZE %zu\n"
           "#define NV2080_GET_ENGINES_count %zu\n#define NV2080_GET_ENGINES_list %zu\n#define NV2080_ENGINE_TYPE_COPY0_ 0x%x\n"
           "#define NV2080_ENGINE_TYPE_COPY_SIZE_ %d\n",
           NV2080_CTRL_CMD_GPU_GET_ENGINES_V2, sizeof(NV2080_CTRL_GPU_GET_ENGINES_V2_PARAMS),
           offsetof(NV2080_CTRL_GPU_GET_ENGINES_V2_PARAMS, engineCount),
           offsetof(NV2080_CTRL_GPU_GET_ENGINES_V2_PARAMS, engineList), NV2080_ENGINE_TYPE_COPY0,
           NV2080_ENGINE_TYPE_COPY_SIZE);
    printf("#define NV2080_CTRL_CMD_CE_GET_FAULT_METHOD_BUFFER_SIZE_ 0x%x\n#define NV2080_CE_MTHDBUF_SIZE %zu\n",
           NV2080_CTRL_CMD_CE_GET_FAULT_METHOD_BUFFER_SIZE, sizeof(NV2080_CTRL_CE_GET_FAULT_METHOD_BUFFER_SIZE_PARAMS));
    printf("#define NVA06F_CTRL_CMD_BIND_ 0x%x\n#define NVA06F_BIND_SIZE %zu\n"
           "#define NVA06F_CTRL_CMD_GPFIFO_SCHEDULE_ 0x%x\n#define NVA06F_SCHEDULE_SIZE %zu\n#define NVA06F_SCHEDULE_bEnable %zu\n"
           "#define NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_ 0x%x\n#define NVC36F_TOKEN_SIZE %zu\n",
           NVA06F_CTRL_CMD_BIND, sizeof(NVA06F_CTRL_BIND_PARAMS), NVA06F_CTRL_CMD_GPFIFO_SCHEDULE,
           sizeof(NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS), offsetof(NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS, bEnable),
           NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN, sizeof(NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS));
    printf("#define NVB0B5_ALLOC_SIZE %zu\n#define NVB0B5_ALLOC_VERSION_1 %d\n",
           sizeof(NVB0B5_ALLOCATION_PARAMETERS), NVB0B5_ALLOCATION_PARAMETERS_VERSION_1);
    printf("#define NVC46F_USERD_GPGet 0x%zx\n#define NVC46F_USERD_GPPut 0x%zx\n",
           offsetof(Nvc46fControl, GPGet), offsetof(Nvc46fControl, GPPut));

    printf("\n// Graphics context buffers and compute (Phase 4 step 7)\n");
    printf("#define TURING_COMPUTE_A_CLASS 0x%x\n", TURING_COMPUTE_A);
    printf("#define NV2080_CTRL_CMD_INTERNAL_STATIC_KGR_GET_CONTEXT_BUFFERS_INFO_ 0x%x\n"
           "#define NV2080_GR_CTXBUF_INFO_SIZE %zu\n#define NV2080_GR_CTXBUF_ENGINE_COUNT %d\n"
           "#define NV2080_GR_CTXBUF_ENTRY_SIZE %zu\n#define NV2080_GR_CTXBUF_PER_GR_SIZE %zu\n",
           NV2080_CTRL_CMD_INTERNAL_STATIC_KGR_GET_CONTEXT_BUFFERS_INFO,
           sizeof(NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS),
           NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_COUNT,
           sizeof(NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO),
           sizeof(NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO));
    printf("#define GR_CTXBUF_GRAPHICS %d\n#define GR_CTXBUF_PATCH %d\n#define GR_CTXBUF_BUNDLE_CB %d\n"
           "#define GR_CTXBUF_PAGEPOOL_GLOBAL %d\n#define GR_CTXBUF_ATTRIBUTE_CB %d\n#define GR_CTXBUF_RTV_CB_GLOBAL %d\n"
           "#define GR_CTXBUF_FECS_EVENT %d\n#define GR_CTXBUF_PRIV_ACCESS_MAP %d\n",
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_PATCH,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_BUNDLE_CB,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_PAGEPOOL_GLOBAL,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_ATTRIBUTE_CB,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_RTV_CB_GLOBAL,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_FECS_EVENT,
           NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_PRIV_ACCESS_MAP);
    typedef NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS P;
    typedef NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY E;
    printf("#define NV2080_CTRL_CMD_GPU_PROMOTE_CTX_ 0x%x\n#define NV2080_PROMOTE_SIZE %zu\n"
           "#define NV2080_PROMOTE_engineType %zu\n#define NV2080_PROMOTE_hChanClient %zu\n#define NV2080_PROMOTE_hObject %zu\n"
           "#define NV2080_PROMOTE_entryCount %zu\n#define NV2080_PROMOTE_entries %zu\n#define NV2080_PROMOTE_MAX %d\n",
           NV2080_CTRL_CMD_GPU_PROMOTE_CTX, sizeof(P), offsetof(P, engineType), offsetof(P, hChanClient),
           offsetof(P, hObject), offsetof(P, entryCount), offsetof(P, promoteEntry),
           NV2080_CTRL_GPU_PROMOTE_CONTEXT_MAX_ENTRIES);
    printf("#define NV2080_PROMOTE_ENTRY_SIZE %zu\n#define NV2080_PE_gpuPhysAddr %zu\n#define NV2080_PE_gpuVirtAddr %zu\n"
           "#define NV2080_PE_size %zu\n#define NV2080_PE_physAttr %zu\n#define NV2080_PE_bufferId %zu\n"
           "#define NV2080_PE_bInitialize %zu\n#define NV2080_PE_bNonmapped %zu\n",
           sizeof(E), offsetof(E, gpuPhysAddr), offsetof(E, gpuVirtAddr), offsetof(E, size), offsetof(E, physAttr),
           offsetof(E, bufferId), offsetof(E, bInitialize), offsetof(E, bNonmapped));
    printf("#define PROMOTE_ID_MAIN %u\n#define PROMOTE_ID_PATCH %u\n#define PROMOTE_ID_BUNDLE_CB %u\n"
           "#define PROMOTE_ID_PAGEPOOL %u\n#define PROMOTE_ID_ATTRIBUTE_CB %u\n#define PROMOTE_ID_RTV_CB_GLOBAL %u\n"
           "#define PROMOTE_ID_PRIV_ACCESS_MAP %u\n#define PROMOTE_ID_UNRESTRICTED_PRIV_ACCESS_MAP %u\n",
           NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_MAIN, NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_PATCH,
           NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_BUFFER_BUNDLE_CB, NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_PAGEPOOL,
           NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_ATTRIBUTE_CB, NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_RTV_CB_GLOBAL,
           NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_PRIV_ACCESS_MAP,
           NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ID_UNRESTRICTED_PRIV_ACCESS_MAP);
    printf("#define NV2080_CTRL_GPU_INITIALIZE_CTX_VIDMEM_UNCACHED 0x%x\n",
           (NV2080_CTRL_GPU_INITIALIZE_CTX_APERTURE_VIDMEM << 0) | (NV2080_CTRL_GPU_INITIALIZE_CTX_GPU_CACHEABLE_NO << 2));
    printf("// The single-buffer form of PROMOTE_CTX (falcon engines such as NVDEC: entryCount 0)\n"
           "#define NV2080_PROMOTE_hClient %zu\n#define NV2080_PROMOTE_ChID %zu\n"
           "#define NV2080_PROMOTE_virtAddress %zu\n#define NV2080_PROMOTE_size %zu\n",
           offsetof(P, hClient), offsetof(P, ChID), offsetof(P, virtAddress), offsetof(P, size));
    printf("#define NV2080_ENGINE_TYPE_GR0_ 0x%x\n", NV2080_ENGINE_TYPE_GR0);
    printf("#define NVC5C0_SET_REPORT_SEMAPHORE_A_ 0x%x\n#define NVC5C0_SEMAPHORE_D_RELEASE_ONE_WORD 0x%x\n",
           NVC5C0_SET_REPORT_SEMAPHORE_A, (NVC5C0_SET_REPORT_SEMAPHORE_D_OPERATION_RELEASE << 0) |
           (NVC5C0_SET_REPORT_SEMAPHORE_D_STRUCTURE_SIZE_ONE_WORD << 28));
    printf("\n// Video decode (NVDEC0). Turing's class is NVC4B0 on every chip (g_gpu_class_list.c, r570).\n"
           "// The channel's engine context is one falcon buffer, sized by GET_CONSTRUCTED_FALCON_INFO for\n"
           "// the engine's ENG_DESC, which comes from the device info table (as nouveau's r570 fifo.c).\n");
    printf("#define NV2080_ENGINE_TYPE_NVDEC0_ 0x%x\n", NV2080_ENGINE_TYPE_NVDEC0);
    // Not in the SDK headers: src/nvidia/inc/kernel/gpu/gpu_engine_type.h and fifo/engine_info.h
    // (both pinned by gsp_abi_check.c).
    printf("#define RM_ENGINE_TYPE_NVDEC0_ 0x1d                     // gpu_engine_type.h (device info table)\n");
    printf("#define NVC4B0_VIDEO_DECODER_CLASS 0x%x\n", NVC4B0_VIDEO_DECODER);
    printf("#define NV_BSP_ALLOC_SIZE %zu                            // NV_BSP_ALLOCATION_PARAMETERS\n"
           "#define NV_BSP_size %zu\n#define NV_BSP_engineInstance %zu\n",
           sizeof(NV_BSP_ALLOCATION_PARAMETERS), offsetof(NV_BSP_ALLOCATION_PARAMETERS, size),
           offsetof(NV_BSP_ALLOCATION_PARAMETERS, engineInstance));
    typedef NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS DI;
    printf("#define NV2080_CTRL_CMD_FIFO_GET_DEVICE_INFO_TABLE_ 0x%x\n#define NV2080_DEVINFO_SIZE %zu\n"
           "#define NV2080_DEVINFO_baseIndex %zu\n#define NV2080_DEVINFO_numEntries %zu\n#define NV2080_DEVINFO_bMore %zu\n"
           "#define NV2080_DEVINFO_entries %zu\n#define NV2080_DEVINFO_MAX %d\n"
           "#define NV2080_DEVINFO_ENTRY_SIZE %zu                   // engineData[16], pbdma ids, name[16]\n",
           NV2080_CTRL_CMD_FIFO_GET_DEVICE_INFO_TABLE, sizeof(DI), offsetof(DI, baseIndex), offsetof(DI, numEntries),
           offsetof(DI, bMore), offsetof(DI, entries), NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_MAX_ENTRIES,
           sizeof(NV2080_CTRL_FIFO_DEVICE_ENTRY));
    printf("#define ENGINE_INFO_TYPE_ENG_DESC_ 0                    // engineData indices (engine_info.h)\n"
           "#define ENGINE_INFO_TYPE_RM_ENGINE_TYPE_ 2\n");
    typedef NV2080_CTRL_GPU_GET_CONSTRUCTED_FALCON_INFO_PARAMS FI;
    typedef NV2080_CTRL_GPU_CONSTRUCTED_FALCON_INFO FE;
    printf("#define NV2080_CTRL_CMD_GPU_GET_CONSTRUCTED_FALCON_INFO_ 0x%x\n#define NV2080_FALCON_INFO_SIZE %zu\n"
           "#define NV2080_FALCON_INFO_count %zu\n#define NV2080_FALCON_INFO_table %zu\n#define NV2080_FALCON_INFO_MAX %d\n"
           "#define NV2080_FALCON_ENTRY_SIZE %zu\n#define NV2080_FALCON_engDesc %zu\n#define NV2080_FALCON_ctxBufferSize %zu\n",
           NV2080_CTRL_CMD_GPU_GET_CONSTRUCTED_FALCON_INFO, sizeof(FI), offsetof(FI, numConstructedFalcons),
           offsetof(FI, constructedFalconsTable), NV2080_CTRL_GPU_MAX_CONSTRUCTED_FALCONS, sizeof(FE),
           offsetof(FE, engDesc), offsetof(FE, ctxBufferSize));
    printf("\n// Display (B0 probe): display instance memory, NV04_DISPLAY_COMMON and its read-only controls,\n"
           "// in the order nouveau's r535_disp_oneinit uses them.\n");
    typedef NV2080_CTRL_INTERNAL_DISPLAY_WRITE_INST_MEM_PARAMS WI;
    printf("#define NV2080_CTRL_CMD_INTERNAL_DISPLAY_WRITE_INST_MEM_ 0x%x\n#define NV2080_DISP_INST_SIZE %zu\n"
           "#define NV2080_DISP_INST_physAddr %zu\n#define NV2080_DISP_INST_size %zu\n"
           "#define NV2080_DISP_INST_addrSpace %zu\n#define NV2080_DISP_INST_cacheAttr %zu\n",
           NV2080_CTRL_CMD_INTERNAL_DISPLAY_WRITE_INST_MEM, sizeof(WI), offsetof(WI, instMemPhysAddr),
           offsetof(WI, instMemSize), offsetof(WI, instMemAddrSpace), offsetof(WI, instMemCpuCacheAttr));
    printf("#define NV04_DISPLAY_COMMON_CLASS 0x%x\n", NV04_DISPLAY_COMMON);
    typedef NV0073_CTRL_SYSTEM_GET_NUM_HEADS_PARAMS NH;
    printf("#define NV0073_CTRL_CMD_SYSTEM_GET_NUM_HEADS_ 0x%x\n#define NV0073_NUM_HEADS_SIZE %zu\n"
           "#define NV0073_NUM_HEADS_numHeads %zu\n",
           NV0073_CTRL_CMD_SYSTEM_GET_NUM_HEADS, sizeof(NH), offsetof(NH, numHeads));
    typedef NV0073_CTRL_SPECIFIC_GET_ALL_HEAD_MASK_PARAMS HM;
    printf("#define NV0073_CTRL_CMD_SPECIFIC_GET_ALL_HEAD_MASK_ 0x%x\n#define NV0073_HEAD_MASK_SIZE %zu\n"
           "#define NV0073_HEAD_MASK_headMask %zu\n",
           NV0073_CTRL_CMD_SPECIFIC_GET_ALL_HEAD_MASK, sizeof(HM), offsetof(HM, headMask));
    typedef NV0073_CTRL_SYSTEM_GET_SUPPORTED_PARAMS SU;
    printf("#define NV0073_CTRL_CMD_SYSTEM_GET_SUPPORTED_ 0x%x\n#define NV0073_SUPPORTED_SIZE %zu\n"
           "#define NV0073_SUPPORTED_displayMask %zu\n#define NV0073_SUPPORTED_displayMaskDDC %zu\n",
           NV0073_CTRL_CMD_SYSTEM_GET_SUPPORTED, sizeof(SU), offsetof(SU, displayMask), offsetof(SU, displayMaskDDC));
    typedef NV0073_CTRL_SYSTEM_GET_CONNECT_STATE_PARAMS CS;
    printf("#define NV0073_CTRL_CMD_SYSTEM_GET_CONNECT_STATE_ 0x%x\n#define NV0073_CONNECT_SIZE %zu\n"
           "#define NV0073_CONNECT_displayMask %zu\n",
           NV0073_CTRL_CMD_SYSTEM_GET_CONNECT_STATE, sizeof(CS), offsetof(CS, displayMask));
    typedef NV0073_CTRL_SPECIFIC_OR_GET_INFO_PARAMS OI;
    printf("#define NV0073_CTRL_CMD_SPECIFIC_OR_GET_INFO_ 0x%x\n#define NV0073_OR_INFO_SIZE %zu\n"
           "#define NV0073_OR_INFO_displayId %zu\n#define NV0073_OR_INFO_index %zu\n#define NV0073_OR_INFO_type %zu\n"
           "#define NV0073_OR_INFO_protocol %zu\n#define NV0073_OR_INFO_location %zu\n#define NV0073_OR_INFO_dcbIndex %zu\n"
           "#define NV0073_OR_INFO_bIsLitByVbios %zu\n",
           NV0073_CTRL_CMD_SPECIFIC_OR_GET_INFO, sizeof(OI), offsetof(OI, displayId), offsetof(OI, index),
           offsetof(OI, type), offsetof(OI, protocol), offsetof(OI, location), offsetof(OI, dcbIndex),
           offsetof(OI, bIsLitByVbios));
    typedef NV0073_CTRL_SPECIFIC_GET_CONNECTOR_DATA_PARAMS CD;
    printf("#define NV0073_CTRL_CMD_SPECIFIC_GET_CONNECTOR_DATA_ 0x%x\n#define NV0073_CONNECTOR_SIZE %zu\n"
           "#define NV0073_CONNECTOR_displayId %zu\n#define NV0073_CONNECTOR_count %zu\n#define NV0073_CONNECTOR_data %zu\n"
           "#define NV0073_CONNECTOR_ENTRY_SIZE %zu\n#define NV0073_CONNECTOR_MAX %d\n#define NV0073_CONNECTOR_platform %zu\n",
           NV0073_CTRL_CMD_SPECIFIC_GET_CONNECTOR_DATA, sizeof(CD), offsetof(CD, displayId), offsetof(CD, count),
           offsetof(CD, data), sizeof(((CD *)0)->data[0]), NV0073_CTRL_MAX_CONNECTORS, offsetof(CD, platform));
    typedef NV0073_CTRL_SPECIFIC_GET_EDID_V2_PARAMS ED;
    printf("#define NV0073_CTRL_CMD_SPECIFIC_GET_EDID_V2_ 0x%x\n#define NV0073_EDID_SIZE %zu\n"
           "#define NV0073_EDID_displayId %zu\n#define NV0073_EDID_bufferSize %zu\n#define NV0073_EDID_buffer %zu\n"
           "#define NV0073_EDID_MAX %d\n",
           NV0073_CTRL_CMD_SPECIFIC_GET_EDID_V2, sizeof(ED), offsetof(ED, displayId), offsetof(ED, bufferSize),
           offsetof(ED, edidBuffer), NV0073_CTRL_SPECIFIC_GET_EDID_MAX_EDID_BYTES);
    typedef NV0073_CTRL_SYSTEM_GET_ACTIVE_PARAMS AC;
    printf("#define NV0073_CTRL_CMD_SYSTEM_GET_ACTIVE_ 0x%x\n#define NV0073_ACTIVE_SIZE %zu\n"
           "#define NV0073_ACTIVE_head %zu\n#define NV0073_ACTIVE_displayId %zu\n",
           NV0073_CTRL_CMD_SYSTEM_GET_ACTIVE, sizeof(AC), offsetof(AC, head), offsetof(AC, displayId));
    printf("\n// Phase 5: GR unit counts, 3D class, host and copy-engine methods used by the kernel\n");
    printf("#define TURING_A_CLASS 0x%x\n", TURING_A);
    printf("#define NV2080_CTRL_CMD_GR_GET_INFO_V2_ 0x%x\n#define NV2080_GR_INFO_V2_SIZE %zu\n"
           "#define NV2080_GR_INFO_V2_listSize %zu\n#define NV2080_GR_INFO_V2_list %zu\n#define NV2080_GR_INFO_ENTRY_SIZE %zu\n"
           "#define NV2080_GR_INFO_MAX %d\n",
           NV2080_CTRL_CMD_GR_GET_INFO_V2, sizeof(NV2080_CTRL_GR_GET_INFO_V2_PARAMS),
           offsetof(NV2080_CTRL_GR_GET_INFO_V2_PARAMS, grInfoListSize), offsetof(NV2080_CTRL_GR_GET_INFO_V2_PARAMS, grInfoList),
           sizeof(NV2080_CTRL_GR_INFO), NV2080_CTRL_GR_INFO_MAX_SIZE);
    printf("#define GR_INFO_SHADER_PIPE_COUNT %d\n#define GR_INFO_SHADER_PIPE_SUB_COUNT %d\n#define GR_INFO_SM_VERSION %d\n"
           "#define GR_INFO_MAX_WARPS_PER_SM %d\n#define GR_INFO_LITTER_NUM_GPCS %d\n#define GR_INFO_LITTER_NUM_SM_PER_TPC %d\n"
           "#define GR_INFO_GPU_CORE_COUNT %d\n",
           NV2080_CTRL_GR_INFO_INDEX_SHADER_PIPE_COUNT, NV2080_CTRL_GR_INFO_INDEX_SHADER_PIPE_SUB_COUNT,
           NV2080_CTRL_GR_INFO_INDEX_SM_VERSION, NV2080_CTRL_GR_INFO_INDEX_MAX_WARPS_PER_SM,
           NV2080_CTRL_GR_INFO_INDEX_LITTER_NUM_GPCS, NV2080_CTRL_GR_INFO_INDEX_LITTER_NUM_SM_PER_TPC,
           NV2080_CTRL_GR_INFO_INDEX_GPU_CORE_COUNT);
    printf("#define NV2080_CTRL_CMD_GR_GET_GPC_MASK_ 0x%x\n#define NV2080_GPC_MASK_SIZE %zu\n#define NV2080_GPC_MASK_gpcMask %zu\n",
           NV2080_CTRL_CMD_GR_GET_GPC_MASK, sizeof(NV2080_CTRL_GR_GET_GPC_MASK_PARAMS),
           offsetof(NV2080_CTRL_GR_GET_GPC_MASK_PARAMS, gpcMask));
    printf("#define NV2080_CTRL_CMD_GR_GET_TPC_MASK_ 0x%x\n#define NV2080_TPC_MASK_SIZE %zu\n#define NV2080_TPC_MASK_gpcId %zu\n"
           "#define NV2080_TPC_MASK_tpcMask %zu\n",
           NV2080_CTRL_CMD_GR_GET_TPC_MASK, sizeof(NV2080_CTRL_GR_GET_TPC_MASK_PARAMS),
           offsetof(NV2080_CTRL_GR_GET_TPC_MASK_PARAMS, gpcId), offsetof(NV2080_CTRL_GR_GET_TPC_MASK_PARAMS, tpcMask));
    printf("#define NVC46F_MEM_OP_A_ 0x%x\n#define NVC46F_MEM_OP_D_MEMBAR 0x%x\n#define NVC46F_SEM_ADDR_LO_ 0x%x\n"
           "#define NVC46F_SEM_EXECUTE_ 0x%x\n#define NVC46F_WFI_ 0x%x\n",
           NVC46F_MEM_OP_A, NVC46F_MEM_OP_D_OPERATION_MEMBAR << 27, NVC46F_SEM_ADDR_LO, NVC46F_SEM_EXECUTE, NVC46F_WFI);
    printf("#define NVC46F_SEM_RELEASE_64_WFI 0x%x\n#define NVC46F_SEM_ACQ_GEQ_64 0x%x\n",
           NVC46F_SEM_EXECUTE_OPERATION_RELEASE | (NVC46F_SEM_EXECUTE_RELEASE_WFI_EN << 20) |
           (NVC46F_SEM_EXECUTE_PAYLOAD_SIZE_64BIT << 24),
           NVC46F_SEM_EXECUTE_OPERATION_ACQ_STRICT_GEQ | (NVC46F_SEM_EXECUTE_ACQUIRE_SWITCH_TSG_EN << 12) |
           (NVC46F_SEM_EXECUTE_PAYLOAD_SIZE_64BIT << 24));
    printf("#define NVC5B5_SET_DST_PHYS_MODE_ 0x%x\n#define NVC5B5_SET_REMAP_CONST_A_ 0x%x\n#define NVC5B5_SET_REMAP_COMPONENTS_ 0x%x\n"
           "#define NVC5B5_REMAP_CONST_A_1B 0x%x\n#define NVC5B5_LAUNCH_MEMSET_PHYS 0x%x\n",
           NVC5B5_SET_DST_PHYS_MODE, NVC5B5_SET_REMAP_CONST_A, NVC5B5_SET_REMAP_COMPONENTS,
           NVC5B5_SET_REMAP_COMPONENTS_DST_X_CONST_A | (NVC5B5_SET_REMAP_COMPONENTS_COMPONENT_SIZE_ONE << 16) |
           (NVC5B5_SET_REMAP_COMPONENTS_NUM_SRC_COMPONENTS_ONE << 20) | (NVC5B5_SET_REMAP_COMPONENTS_NUM_DST_COMPONENTS_ONE << 24),
           NVC5B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED | (NVC5B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE << 2) |
           (NVC5B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE << 3) |
           (NVC5B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH << 7) | (NVC5B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH << 8) |
           (NVC5B5_LAUNCH_DMA_REMAP_ENABLE_TRUE << 10) | (NVC5B5_LAUNCH_DMA_DST_TYPE_PHYSICAL << 13));
    return 0;
}
