// Generated by tools/gsp_layout_probe.c from NVIDIA open-gpu-kernel-modules 570.144
// (MIT). Byte offsets into the GET_GSP_STATIC_INFO payload (GspStaticConfigInfo).
#pragma once

#define GSC_SIZE 1656
#define GSC_grCapsBits                         0x0000  // size 23
#define GSC_gidInfo                            0x0018  // size 268
#define GSC_SKUInfo                            0x0124  // size 48
#define GSC_fbRegionInfoParams                 0x0158  // size 776
#define GSC_sriovCaps                          0x0460  // size 80
#define GSC_sriovMaxGfid                       0x04b0  // size 4
#define GSC_engineCaps                         0x04b4  // size 12
#define GSC_poisonFuseEnabled                  0x04c0  // size 1
#define GSC_fb_length                          0x04c8  // size 8
#define GSC_fbio_mask                          0x04d0  // size 8
#define GSC_fb_bus_width                       0x04d8  // size 4
#define GSC_fb_ram_type                        0x04dc  // size 4
#define GSC_fbp_mask                           0x04e0  // size 8
#define GSC_l2_cache_size                      0x04e8  // size 4
#define GSC_gpuNameString                      0x04ec  // size 64
#define GSC_gpuShortNameString                 0x052c  // size 64
#define GSC_gpuNameString_Unicode              0x056c  // size 128
#define GSC_bGpuInternalSku                    0x05ec  // size 1
#define GSC_bIsQuadroGeneric                   0x05ed  // size 1
#define GSC_bIsQuadroAd                        0x05ee  // size 1
#define GSC_bIsNvidiaNvs                       0x05ef  // size 1
#define GSC_bIsVgx                             0x05f0  // size 1
#define GSC_bGeforceSmb                        0x05f1  // size 1
#define GSC_bIsTitan                           0x05f2  // size 1
#define GSC_bIsTesla                           0x05f3  // size 1
#define GSC_bIsMobile                          0x05f4  // size 1
#define GSC_bIsGc6Rtd3Allowed                  0x05f5  // size 1
#define GSC_bIsGc8Rtd3Allowed                  0x05f6  // size 1
#define GSC_bIsGcOffRtd3Allowed                0x05f7  // size 1
#define GSC_bIsGcoffLegacyAllowed              0x05f8  // size 1
#define GSC_bIsMigSupported                    0x05f9  // size 1
#define GSC_RTD3GC6TotalBoardPower             0x05fa  // size 2
#define GSC_RTD3GC6PerstDelay                  0x05fc  // size 2
#define GSC_bar1PdeBase                        0x0600  // size 8
#define GSC_bar2PdeBase                        0x0608  // size 8
#define GSC_bVbiosValid                        0x0610  // size 1
#define GSC_vbiosSubVendor                     0x0614  // size 4
#define GSC_vbiosSubDevice                     0x0618  // size 4
#define GSC_bPageRetirementSupported           0x061c  // size 1
#define GSC_bSplitVasBetweenServerClientRm     0x061d  // size 1
#define GSC_bClRootportNeedsNosnoopWAR         0x061e  // size 1
#define GSC_displaylessMaxHeads                0x0620  // size 8
#define GSC_displaylessMaxResolution           0x0628  // size 12
#define GSC_displaylessMaxPixels               0x0638  // size 8
#define GSC_hInternalClient                    0x0640  // size 4
#define GSC_hInternalDevice                    0x0644  // size 4
#define GSC_hInternalSubdevice                 0x0648  // size 4
#define GSC_bSelfHostedMode                    0x064c  // size 1
#define GSC_bAtsSupported                      0x064d  // size 1
#define GSC_bIsGpuUefi                         0x064e  // size 1
#define GSC_bIsEfiInit                         0x064f  // size 1
#define GSC_ecidInfo                           0x0650  // size 24
#define GSC_fwWprLayoutOffset                  0x0668  // size 16
#define FBR_PARAMS_SIZE 776

// fbRegionInfoParams (NV2080_CTRL_CMD_FB_GET_FB_REGION_INFO_PARAMS)
#define FBR_NUM 0
#define FBR_REGIONS 8
#define FBR_MAX 16
#define FBR_REGION_SIZE 48
#define FBR_BASE 0
#define FBR_LIMIT 8
#define FBR_RESERVED 16
#define FBR_PERFORMANCE 24
#define FBR_COMPRESSED 28
#define FBR_ISO 29
#define FBR_PROTECTED 30

// Object allocation parameters (GSP_RM_ALLOC payloads)
#define NV01_ROOT_CLASS 0x0
#define NV01_DEVICE_0_CLASS 0x80
#define NV20_SUBDEVICE_0_CLASS 0x2080
#define NV0000_ALLOC_SIZE 120
#define NV0000_hClient 0
#define NV0000_processID 4
#define NV0000_processName 8
#define NV0080_ALLOC_SIZE 56
#define NV0080_deviceId 0
#define NV0080_hClientShare 4
#define NV2080_ALLOC_SIZE 4
#define NV2080_subDeviceId 0

// Controls (GSP_RM_CONTROL payloads)
#define NV2080_CTRL_CMD_GPU_GET_NAME_STRING_ 0x20800110
#define NV2080_GET_NAME_SIZE 132
#define NV2080_GET_NAME_flags 0
#define NV2080_GET_NAME_string 4

// VA space (FERMI_VASPACE_A) and its reserved-PDE control (Phase 4 step 4)
#define FERMI_VASPACE_A_CLASS 0x90f1
#define NV_VASPACE_ALLOC_SIZE 48
#define NV_VASPACE_index 0
#define NV_VASPACE_flags 4
#define NV_VASPACE_vaSize 8
#define NV_VASPACE_bigPageSize 32
#define NV_VASPACE_vaBase 40
#define NV90F1_CTRL_CMD_VASPACE_COPY_SERVER_RESERVED_PDES_ 0x90f10106
#define NV90F1_COPY_PDES_SIZE 184
#define NV90F1_COPY_PDES_hSubDevice 0
#define NV90F1_COPY_PDES_subDeviceId 4
#define NV90F1_COPY_PDES_pageSize 8
#define NV90F1_COPY_PDES_virtAddrLo 16
#define NV90F1_COPY_PDES_virtAddrHi 24
#define NV90F1_COPY_PDES_numLevelsToCopy 32
#define NV90F1_COPY_PDES_levels 40
#define NV90F1_COPY_PDES_LEVEL_SIZE 24
#define NV90F1_COPY_PDES_MAX_LEVELS 6
#define NV90F1_LEVEL_physAddress 40
#define NV90F1_LEVEL_size 48
#define NV90F1_LEVEL_aperture 56
#define NV90F1_LEVEL_pageShift 60

// Channel and copy engine (Phase 4 step 5)
#define TURING_CHANNEL_GPFIFO_A_CLASS 0xc46f
#define TURING_DMA_COPY_A_CLASS 0xc5b5
#define NV_CHAN_ALLOC_SIZE 368
#define NV_CHAN_hObjectError 0
#define NV_CHAN_gpFifoOffset 8
#define NV_CHAN_gpFifoEntries 16
#define NV_CHAN_flags 20
#define NV_CHAN_hContextShare 24
#define NV_CHAN_hVASpace 28
#define NV_CHAN_engineType 128
#define NV_CHAN_subDeviceId 136
#define NV_CHAN_instanceMem 144
#define NV_CHAN_userdMem 168
#define NV_CHAN_ramfcMem 192
#define NV_CHAN_mthdbufMem 216
#define NV_CHAN_internalFlags 244
#define NV_CHAN_errorNotifierMem 248
#define NV_MEMDESC_SIZE 24
#define NV_MEMDESC_base 0
#define NV_MEMDESC_size 8
#define NV_MEMDESC_addressSpace 16
#define NV_MEMDESC_cacheAttrib 20
#define NV2080_CTRL_CMD_GPU_GET_ENGINES_V2_ 0x20800170
#define NV2080_GET_ENGINES_SIZE 340
#define NV2080_GET_ENGINES_count 0
#define NV2080_GET_ENGINES_list 4
#define NV2080_ENGINE_TYPE_COPY0_ 0x9
#define NV2080_ENGINE_TYPE_COPY_SIZE_ 64
#define NV2080_CTRL_CMD_CE_GET_FAULT_METHOD_BUFFER_SIZE_ 0x20802a08
#define NV2080_CE_MTHDBUF_SIZE 4
#define NVA06F_CTRL_CMD_BIND_ 0xa06f0104
#define NVA06F_BIND_SIZE 4
#define NVA06F_CTRL_CMD_GPFIFO_SCHEDULE_ 0xa06f0103
#define NVA06F_SCHEDULE_SIZE 2
#define NVA06F_SCHEDULE_bEnable 0
#define NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_ 0xc36f0108
#define NVC36F_TOKEN_SIZE 4
#define NVB0B5_ALLOC_SIZE 8
#define NVB0B5_ALLOC_VERSION_1 1
#define NVC46F_USERD_GPGet 0x88
#define NVC46F_USERD_GPPut 0x8c

// Graphics context buffers and compute (Phase 4 step 7)
#define TURING_COMPUTE_A_CLASS 0xc5c0
#define NV2080_CTRL_CMD_INTERNAL_STATIC_KGR_GET_CONTEXT_BUFFERS_INFO_ 0x20800a32

// NV2080_CTRL_CMD_INTERNAL_INTR_GET_KERNEL_TABLE (ctrl2080internal.h, r570), on GSP-RM's internal
// client: the interrupt vectors kernel RM (the CPU) services. Params: u32 tableLen, 128 entries of
// {u16 engineIdx, u32 pmcIntrMask, u32 vectorStall, u32 vectorNonStall} (16 bytes, 4-aligned),
// then subtreeMap[7] of {u8 start, u8 end} per NV2080_INTR_CATEGORY.
#define NV2080_CTRL_CMD_INTERNAL_INTR_GET_KERNEL_TABLE_ 0x20800a5c
#define NV2080_INTR_TABLE_MAX          128
#define NV2080_INTR_TABLE_ENTRY_SIZE   16
#define NV2080_INTR_TABLE_SUBTREE_OFF  (4 + NV2080_INTR_TABLE_MAX * NV2080_INTR_TABLE_ENTRY_SIZE)
#define NV2080_INTR_CATEGORY_COUNT     7
#define NV2080_INTR_TABLE_SIZE         ((NV2080_INTR_TABLE_SUBTREE_OFF + NV2080_INTR_CATEGORY_COUNT * 2 + 3) & ~3)
#define NV_INTR_VECTOR_INVALID         0xffffffffu
#define MC_ENGINE_IDX_CE0_             15       // engine_idx.h: CE0..CE9 = 15..24
#define MC_ENGINE_IDX_GR0_             84
#define MC_ENGINE_IDX_NVDEC0_          65       // engine_idx.h: MC_ENGINE_IDX_BSP
#define NV2080_GR_CTXBUF_INFO_SIZE 1664
#define NV2080_GR_CTXBUF_ENGINE_COUNT 26
#define NV2080_GR_CTXBUF_ENTRY_SIZE 8
#define NV2080_GR_CTXBUF_PER_GR_SIZE 208
#define GR_CTXBUF_GRAPHICS 0
#define GR_CTXBUF_PATCH 16
#define GR_CTXBUF_BUNDLE_CB 17
#define GR_CTXBUF_PAGEPOOL_GLOBAL 18
#define GR_CTXBUF_ATTRIBUTE_CB 19
#define GR_CTXBUF_RTV_CB_GLOBAL 20
#define GR_CTXBUF_FECS_EVENT 23
#define GR_CTXBUF_PRIV_ACCESS_MAP 24
#define NV2080_CTRL_CMD_GPU_PROMOTE_CTX_ 0x2080012b
// P-state boost (what CPU-RM's NV2080_CTRL_CMD_PERF_BOOST sends to GSP-RM) and the current P-state
#define NV2080_CTRL_CMD_INTERNAL_PERF_BOOST_SET_2X_ 0x20800a9a
struct NV2080_CTRL_INTERNAL_PERF_BOOST_SET_PARAMS_2X_ {
    uint8_t  flags;         // NvBool in the SDK; carries NV2080_CTRL_PERF_BOOST_FLAGS_CMD
    uint8_t  pad[3];
    uint32_t duration;      // seconds, or 0xffffffff until cleared
};
static_assert(sizeof(NV2080_CTRL_INTERNAL_PERF_BOOST_SET_PARAMS_2X_) == 8, "PERF_BOOST_SET_2X");
#define NV2080_CTRL_CMD_PERF_GET_CURRENT_PSTATE_ 0x20802068     // NvU32 currPstate: bit n = Pn
#define NV2080_PROMOTE_SIZE 560
#define NV2080_PROMOTE_engineType 0
#define NV2080_PROMOTE_hChanClient 12
#define NV2080_PROMOTE_hObject 16
#define NV2080_PROMOTE_entryCount 40
#define NV2080_PROMOTE_entries 48
#define NV2080_PROMOTE_MAX 16
#define NV2080_PROMOTE_ENTRY_SIZE 32
#define NV2080_PE_gpuPhysAddr 0
#define NV2080_PE_gpuVirtAddr 8
#define NV2080_PE_size 16
#define NV2080_PE_physAttr 24
#define NV2080_PE_bufferId 28
#define NV2080_PE_bInitialize 30
#define NV2080_PE_bNonmapped 31
#define PROMOTE_ID_MAIN 0
#define PROMOTE_ID_PATCH 2
#define PROMOTE_ID_BUNDLE_CB 3
#define PROMOTE_ID_PAGEPOOL 4
#define PROMOTE_ID_ATTRIBUTE_CB 5
#define PROMOTE_ID_RTV_CB_GLOBAL 6
#define PROMOTE_ID_PRIV_ACCESS_MAP 10
#define PROMOTE_ID_UNRESTRICTED_PRIV_ACCESS_MAP 11
#define NV2080_CTRL_GPU_INITIALIZE_CTX_VIDMEM_UNCACHED 0x4
// The single-buffer form of PROMOTE_CTX (falcon engines such as NVDEC: entryCount 0)
#define NV2080_PROMOTE_hClient 4
#define NV2080_PROMOTE_ChID 8
#define NV2080_PROMOTE_virtAddress 24
#define NV2080_PROMOTE_size 32
#define NV2080_ENGINE_TYPE_GR0_ 0x1
#define NVC5C0_SET_REPORT_SEMAPHORE_A_ 0x1b00
#define NVC5C0_SEMAPHORE_D_RELEASE_ONE_WORD 0x10000000

// Video decode (NVDEC0). Turing's class is NVC4B0 on every chip (g_gpu_class_list.c, r570).
// The channel's engine context is one falcon buffer, sized by GET_CONSTRUCTED_FALCON_INFO for
// the engine's ENG_DESC, which comes from the device info table (as nouveau's r570 fifo.c).
#define NV2080_ENGINE_TYPE_NVDEC0_ 0x13
#define RM_ENGINE_TYPE_NVDEC0_ 0x1d                     // gpu_engine_type.h (device info table)
#define NVC4B0_VIDEO_DECODER_CLASS 0xc4b0
#define NV_BSP_ALLOC_SIZE 12                            // NV_BSP_ALLOCATION_PARAMETERS
#define NV_BSP_size 0
#define NV_BSP_engineInstance 8
#define NV2080_CTRL_CMD_FIFO_GET_DEVICE_INFO_TABLE_ 0x20801112
#define NV2080_DEVINFO_SIZE 3212
#define NV2080_DEVINFO_baseIndex 0
#define NV2080_DEVINFO_numEntries 4
#define NV2080_DEVINFO_bMore 8
#define NV2080_DEVINFO_entries 12
#define NV2080_DEVINFO_MAX 32
#define NV2080_DEVINFO_ENTRY_SIZE 100                   // engineData[16], pbdma ids, name[16]
#define ENGINE_INFO_TYPE_ENG_DESC_ 0                    // engineData indices (engine_info.h)
#define ENGINE_INFO_TYPE_RM_ENGINE_TYPE_ 2
#define NV2080_CTRL_CMD_GPU_GET_CONSTRUCTED_FALCON_INFO_ 0x208001b0
#define NV2080_FALCON_INFO_SIZE 1284
#define NV2080_FALCON_INFO_count 0
#define NV2080_FALCON_INFO_table 4
#define NV2080_FALCON_INFO_MAX 64
#define NV2080_FALCON_ENTRY_SIZE 20
#define NV2080_FALCON_engDesc 0
#define NV2080_FALCON_ctxBufferSize 8

// Display (B0 probe): display instance memory, NV04_DISPLAY_COMMON and its read-only controls,
// in the order nouveau's r535_disp_oneinit uses them.
#define NV2080_CTRL_CMD_INTERNAL_DISPLAY_WRITE_INST_MEM_ 0x20800a49
#define NV2080_DISP_INST_SIZE 24
#define NV2080_DISP_INST_physAddr 0
#define NV2080_DISP_INST_size 8
#define NV2080_DISP_INST_addrSpace 16
#define NV2080_DISP_INST_cacheAttr 20
#define NV04_DISPLAY_COMMON_CLASS 0x73
#define NV0073_CTRL_CMD_SYSTEM_GET_NUM_HEADS_ 0x730102
#define NV0073_NUM_HEADS_SIZE 12
#define NV0073_NUM_HEADS_numHeads 8
#define NV0073_CTRL_CMD_SPECIFIC_GET_ALL_HEAD_MASK_ 0x730287
#define NV0073_HEAD_MASK_SIZE 8
#define NV0073_HEAD_MASK_headMask 4
#define NV0073_CTRL_CMD_SYSTEM_GET_SUPPORTED_ 0x730107
#define NV0073_SUPPORTED_SIZE 12
#define NV0073_SUPPORTED_displayMask 4
#define NV0073_SUPPORTED_displayMaskDDC 8
#define NV0073_CTRL_CMD_SYSTEM_GET_CONNECT_STATE_ 0x730108
#define NV0073_CONNECT_SIZE 16
#define NV0073_CONNECT_displayMask 8
#define NV0073_CTRL_CMD_SPECIFIC_OR_GET_INFO_ 0x73028b
#define NV0073_OR_INFO_SIZE 56
#define NV0073_OR_INFO_displayId 4
#define NV0073_OR_INFO_index 8
#define NV0073_OR_INFO_type 12
#define NV0073_OR_INFO_protocol 16
#define NV0073_OR_INFO_location 28
#define NV0073_OR_INFO_dcbIndex 36
#define NV0073_OR_INFO_bIsLitByVbios 48
#define NV0073_CTRL_CMD_SPECIFIC_GET_CONNECTOR_DATA_ 0x730250
#define NV0073_CONNECTOR_SIZE 72
#define NV0073_CONNECTOR_displayId 4
#define NV0073_CONNECTOR_count 16
#define NV0073_CONNECTOR_data 20
#define NV0073_CONNECTOR_ENTRY_SIZE 12
#define NV0073_CONNECTOR_MAX 4
#define NV0073_CONNECTOR_platform 68
#define NV0073_CTRL_CMD_SPECIFIC_GET_EDID_V2_ 0x730245
#define NV0073_EDID_SIZE 2064
#define NV0073_EDID_displayId 4
#define NV0073_EDID_bufferSize 8
#define NV0073_EDID_buffer 16
#define NV0073_EDID_MAX 2048
#define NV0073_CTRL_CMD_SYSTEM_GET_ACTIVE_ 0x73010c
#define NV0073_ACTIVE_SIZE 16
#define NV0073_ACTIVE_head 4
#define NV0073_ACTIVE_displayId 12

// Phase 5: GR unit counts, 3D class, host and copy-engine methods used by the kernel
#define TURING_A_CLASS 0xc597
#define NV2080_CTRL_CMD_GR_GET_INFO_V2_ 0x20801228
#define NV2080_GR_INFO_V2_SIZE 488
#define NV2080_GR_INFO_V2_listSize 0
#define NV2080_GR_INFO_V2_list 4
#define NV2080_GR_INFO_ENTRY_SIZE 8
#define NV2080_GR_INFO_MAX 58
#define GR_INFO_SHADER_PIPE_COUNT 7
#define GR_INFO_SHADER_PIPE_SUB_COUNT 9
#define GR_INFO_SM_VERSION 12
#define GR_INFO_MAX_WARPS_PER_SM 13
#define GR_INFO_LITTER_NUM_GPCS 20
#define GR_INFO_LITTER_NUM_SM_PER_TPC 32
#define GR_INFO_GPU_CORE_COUNT 29
#define NV2080_CTRL_CMD_GR_GET_GPC_MASK_ 0x2080122a
#define NV2080_GPC_MASK_SIZE 24
#define NV2080_GPC_MASK_gpcMask 16
#define NV2080_CTRL_CMD_GR_GET_TPC_MASK_ 0x2080122b
#define NV2080_TPC_MASK_SIZE 24
#define NV2080_TPC_MASK_gpcId 16
#define NV2080_TPC_MASK_tpcMask 20
#define NVC46F_MEM_OP_A_ 0x28
#define NVC46F_MEM_OP_D_MEMBAR 0x28000000
#define NVC46F_SEM_ADDR_LO_ 0x5c
#define NVC46F_SEM_EXECUTE_ 0x6c
#define NVC46F_WFI_ 0x78
#define NVC46F_NON_STALL_INTERRUPT_ 0x20
#define NVC46F_SEM_RELEASE_64_WFI 0x1100001
#define NVC46F_SEM_ACQ_GEQ_64 0x1001002
#define NVC5B5_SET_DST_PHYS_MODE_ 0x264
#define NVC5B5_SET_REMAP_CONST_A_ 0x700
#define NVC5B5_SET_REMAP_COMPONENTS_ 0x708
#define NVC5B5_REMAP_CONST_A_1B 0x4
#define NVC5B5_LAUNCH_MEMSET_PHYS 0x258e
